### ISSUE TITLE
RC for CMSAF HOAPS

### ISSUE THREAD

**Issue by Funkensieper** [PCMDI/obs4MIPs-cmor-tables#109] opened 2017-09-28 09:55 UTC
1) source_name = 'CMSAF-HOAPS'
2) release_year = '2017'
3) source_description = 'Hamburg Ocean Atmosphere Parameters and fluxes from Satellite data. Based on SSM/I and SSMIS aboard DMSP.'
4) source_version_number = '4.0'
5) institution_id = 'DWD'
6) region = 'global_ocean'
7) source_type = 'satellite_retrieval'

nobs: pme, sfcWind, pr, huss, hfls, evspsbl, hfss, prw
stddev: pme, sfcWind, pr, huss, hfls, evspsbl, hfss, prw
stderr: sfcWind, huss, hfls, evspsbl

**Comment by Funkensieper** [comment] 2017-10-04 10:02
8. pme, sfcWind, pr, huss, hfls, evspsbl, hfss, prw

**Comment by gleckler1** [comment] 2017-10-04 19:31
@Funkensieper  # 109-111 will be closed as all source_ids have been updated.  However, the question of how to accommodate the ancillary fields (Nobs, stderr, SD?) needs to be addressed by the WDAC task team so that will be consolidated into Issue #123

**Closed by gleckler1** 2017-10-04 19:31 UTC

**Comment by Funkensieper** [comment] 2017-12-12 10:44
Unfortunately, it is not possible to specify a certain altitude for HOAPS ``huss`` as it corresponds roughly to the "lowest atmospheric layer". Is that still acceptable? We would add a comment to the variable's attributes and explain the reason in the technical note.

**Comment by durack1** [comment] 2017-12-12 15:04
@Funkensieper there is a way to include a singleton dimension, for `huss` the default is `height2m` see [here](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_Amon.json#L664-L680). This should then provide the following information in the output file:
```
...
	double time(time) ;
		time:units = "days since 1900-01-01 00:00:00" ;
		time:axis = "T" ;
		time:cartesian_axis = "T" ;
		time:bounds = "time_bnds" ;
		time:calendar = "gregorian" ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
	double height(height) ;
		height:long_name = "height" ;
		height:standard_name = "height" ;
		height:units = "m" ;
		height:axis = "Z" ;
	double time_bnds(time, time_bnds_dim) ;
		time_bnds:long_name = "Time boundaries" ;
	float huss(time, latitude, longitude) ;
		huss:coordinates = "height" ;
		huss:units = "kg/kg" ;
		huss:long_name = "Near-Surface Specific Humidity at the 10 meter height" ;
		huss:standard_name = "specific_humidity" ;
		huss:missing_value = -9.99e+33f ;
		huss:_Fill_value = "-9.99e+33f" ;
...
```

**Comment by taylor13** [comment] 2017-12-12 17:11
I think the problem is that in the HOAPS "measurements", the inference of near-surface specific humidity is not accurate enough to assign a specific height at which it is estimated.  I think nothing would break if the singleton dimension were omitted here, and I think that would be less misleading than assigning a specific height.  The long_name should also be revised to omit "at the 10 meter height".

**Comment by Funkensieper** [comment] 2017-12-13 09:04
@durack1 Aha, I didn't know about that!
@taylor13 Exactly. Your suggestion sounds reasonable. Does that imply that a new ``huss`` variable without singleton dimension is needed?

**Comment by taylor13** [comment] 2017-12-13 16:59
I think we can keep the variable name "huss" and the standard_name "specific_humidity".   I would omit the coordinate attribute and the vertical coordinate.   I think an appropriate long_name would be "Near-Surface Specific Humidity".  I think you should add a "comment" variable attribute attached to the variable "huss" and explain there something along the lines "The HOAPS estimate of near surface specific humidity is based on satellite retrievals that do not directly sample humidity at a particular height above the surface.  The near-surface humidity is estimated from radiances determined in part by the amount of humidity found in the layer of air above the surface.  Please read the HOAPS document for guidance on the limitations of the measurement."

**Comment by Funkensieper** [comment] 2017-12-15 08:38
Sorry, there was a misunderstanding on our side. The algorithm ties the retrieved "near surface" humidity to buoy measurements via regression, so the 2m height is suitable. Sorry for the confusion.

**Comment by taylor13** [comment] 2017-12-15 17:23
o.k., then I guess Paul's example above applies (https://github.com/PCMDI/obs4MIPs-cmor-tables/issues/109#issuecomment-351077755) but make sure to correct the long_name to 2 meter (not 10 meter)

**Comment by gleckler1** [comment] 2017-12-15 17:55
I think this is resolved but noting for CMIP it 2m for huss and tas but 10m for uas and vas.

**Comment by Funkensieper** [comment] 2017-12-18 09:02
Thanks for the hint @gleckler1 !

**Comment by durack1** [comment] 2017-12-18 18:20
[huss](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_Amon.json#L664-L680)
[tas](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_Amon.json#L1242-L1258)
[uas](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_Amon.json#L1378-L1394)
[vas](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_Amon.json#L1412-L1428)
